"""Initial schema

Revision ID: 496748f5398d
Revises: 
Create Date: 2026-02-07 14:53:22.236262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '496748f5398d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_country'), 'holidays', ['country'], unique=False)
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_index(op.f('ix_holidays_state'), 'holidays', ['state'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'HR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('attendance_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='attendancetype'), nullable=False),
    sa.Column('mode', sa.Enum('OFFICE', 'FIELD', 'BRANCH', 'WFH', name='workmode'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(), nullable=True),
    sa.Column('field_work_reason', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('verification_method', sa.Enum('BIOMETRIC', 'PIN', 'FACE_ONLY', name='verificationmethod'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_entries_employee_id'), 'attendance_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_entries_id'), 'attendance_entries', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_entries_timestamp'), 'attendance_entries', ['timestamp'], unique=False)
    op.create_table('attendance_locks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_locks_date'), 'attendance_locks', ['date'], unique=True)
    op.create_index(op.f('ix_attendance_locks_id'), 'attendance_locks', ['id'], unique=False)
    op.create_table('employee_week_offs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('week_offs', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_week_offs_id'), 'employee_week_offs', ['id'], unique=False)
    op.create_table('overtime_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_requests_date'), 'overtime_requests', ['date'], unique=False)
    op.create_index(op.f('ix_overtime_requests_employee_id'), 'overtime_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_overtime_requests_id'), 'overtime_requests', ['id'], unique=False)
    op.create_table('permission_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_requests_date'), 'permission_requests', ['date'], unique=False)
    op.create_index(op.f('ix_permission_requests_employee_id'), 'permission_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_permission_requests_id'), 'permission_requests', ['id'], unique=False)
    op.create_table('regularization_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LOGIN', 'LOGOUT', 'BOTH', 'MISSED_CHECKIN', 'MISSED_CHECKOUT', 'FULL_DAY', name='regularizationtype'), nullable=False),
    sa.Column('actual_time', sa.String(), nullable=True),
    sa.Column('requested_login_time', sa.String(), nullable=True),
    sa.Column('requested_logout_time', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regularization_requests_date'), 'regularization_requests', ['date'], unique=False)
    op.create_index(op.f('ix_regularization_requests_employee_id'), 'regularization_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_regularization_requests_id'), 'regularization_requests', ['id'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('shift_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_assignments_date'), 'shift_assignments', ['date'], unique=False)
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_id'), 'shift_assignments', ['id'], unique=False)
    op.create_table('shift_change_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('current_shift_id', sa.String(), nullable=False),
    sa.Column('requested_shift_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['current_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.ForeignKeyConstraint(['requested_shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_change_requests_date'), 'shift_change_requests', ['date'], unique=False)
    op.create_index(op.f('ix_shift_change_requests_employee_id'), 'shift_change_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_change_requests_id'), 'shift_change_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_change_requests_id'), table_name='shift_change_requests')
    op.drop_index(op.f('ix_shift_change_requests_employee_id'), table_name='shift_change_requests')
    op.drop_index(op.f('ix_shift_change_requests_date'), table_name='shift_change_requests')
    op.drop_table('shift_change_requests')
    op.drop_index(op.f('ix_shift_assignments_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_date'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_regularization_requests_id'), table_name='regularization_requests')
    op.drop_index(op.f('ix_regularization_requests_employee_id'), table_name='regularization_requests')
    op.drop_index(op.f('ix_regularization_requests_date'), table_name='regularization_requests')
    op.drop_table('regularization_requests')
    op.drop_index(op.f('ix_permission_requests_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_employee_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_date'), table_name='permission_requests')
    op.drop_table('permission_requests')
    op.drop_index(op.f('ix_overtime_requests_id'), table_name='overtime_requests')
    op.drop_index(op.f('ix_overtime_requests_employee_id'), table_name='overtime_requests')
    op.drop_index(op.f('ix_overtime_requests_date'), table_name='overtime_requests')
    op.drop_table('overtime_requests')
    op.drop_index(op.f('ix_employee_week_offs_id'), table_name='employee_week_offs')
    op.drop_table('employee_week_offs')
    op.drop_index(op.f('ix_attendance_locks_id'), table_name='attendance_locks')
    op.drop_index(op.f('ix_attendance_locks_date'), table_name='attendance_locks')
    op.drop_table('attendance_locks')
    op.drop_index(op.f('ix_attendance_entries_timestamp'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_id'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_employee_id'), table_name='attendance_entries')
    op.drop_table('attendance_entries')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_holidays_state'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_country'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
